#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Convert alternative matches SQL to correct syntax with ::text casting.
Creates compact, runnable SQL with BEGIN/COMMIT.
"""

import re
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

workspace_root = Path(__file__).parent.parent
input_file = workspace_root / "scripts" / "fix_report_filenames_alternative.sql"
output_file = workspace_root / "scripts" / "fix_report_filenames_alternative_CORRECTED.sql"

print("📂 Reading alternative matches SQL file...")
with open(input_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Extract updates using simpler line parsing
lines = content.split('\n')
updates = []
current_domain = None
current_strategy = None

for i, line in enumerate(lines):
    if line.startswith('-- Domain:'):
        # Extract domain and strategy
        parts = line.split('(Strategy:')
        current_domain = parts[0].replace('-- Domain:', '').strip()
        if len(parts) > 1:
            current_strategy = parts[1].strip(' )')
    elif "to_jsonb('" in line:
        # Extract filename
        filename_match = re.search(r"to_jsonb\('([^']+)'\)", line)
        if filename_match:
            filename = filename_match.group(1)
            # Look for WHERE id on next few lines
            for j in range(i, min(i+5, len(lines))):
                id_match = re.search(r"WHERE id = '([^']+)'", lines[j])
                if id_match:
                    lead_id = id_match.group(1)
                    updates.append({
                        'domain': current_domain,
                        'strategy': current_strategy,
                        'filename': filename,
                        'lead_id': lead_id
                    })
                    current_domain = None
                    current_strategy = None
                    break

print(f"✅ Found {len(updates)} alternative match updates")

# Create corrected SQL with BEGIN/COMMIT
print("\n📝 Creating corrected SQL file...")

with open(output_file, 'w', encoding='utf-8') as f:
    f.write("-- CORRECTED SQL updates for alternative matches\n")
    f.write("-- Total updates: 135\n")
    f.write("-- WARNING: These used fuzzy matching - verify results!\n")
    f.write("-- Generated by fix_alternative_matches.py\n\n")
    f.write("BEGIN;\n\n")
    
    for update in updates:
        filename = update['filename']
        lead_id = update['lead_id']
        domain = update['domain']
        
        # Single-line UPDATE with ::text casting
        f.write(f"-- {domain}\n")
        f.write(f"UPDATE leads SET vars = jsonb_set(vars, '{{report_filename}}', to_jsonb('{filename}'::text)) WHERE id = '{lead_id}';\n")
    
    f.write("\nCOMMIT;\n")

print(f"✅ Corrected SQL file created: {output_file}")
print(f"\n📊 SUMMARY:")
print(f"  Total updates: {len(updates)}")
print(f"  File size: ~{len(updates) * 150} bytes")
print("\n📋 INSTRUCTIONS:")
print("1. FIRST verify primary 1067 updates worked correctly")
print("2. Open Supabase SQL Editor")
print("3. Copy ENTIRE content of fix_report_filenames_alternative_CORRECTED.sql")
print("4. Paste into SQL Editor")
print("5. Click 'Run' - updates 135 leads in one transaction")
print("\n⚠️  NOTE: These are fuzzy matches - review results!")
print("="*80)
