-- SQL statements for alternative matches
-- Generated by analyze_not_found.py
-- Total updates: 135
-- WARNING: Review carefully - these used fuzzy matching!

-- Domain: aandacht.net (Strategy: Pattern: 'aandacht')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('aandacht_net_report.pdf')
)
WHERE id = '248ba831-ddb5-414f-ad0e-17deaf9966ad';

-- Domain: alussolighting.store (Strategy: Pattern: 'alussolighting')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('alussolighting_store_nl_nl_products_step_light_report.pdf')
)
WHERE id = '1764a7ae-3e84-4e9f-ae51-7a862ff11ef8';

-- Domain: ambiente.eu (Strategy: Pattern: 'ambiente')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('ambiente_eu_nl_report.pdf')
)
WHERE id = 'e4cc578c-46a3-4afe-8d32-9e5902f3c290';

-- Domain: arsmundi.de (Strategy: Pattern: 'arsmundi')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('arsmundi_de_nl_museumshop_decoratieve_objecten_report.pdf')
)
WHERE id = '328c0c41-35e0-4b69-8760-f418c24707ad';

-- Domain: atmosfire.be (Strategy: Pattern: 'atmosfire')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('atmosfire_be_nl_produit_bengal_fuego_mix_5_pcs_report.pdf')
)
WHERE id = '6760b85c-9791-408b-a7c5-364eb4afe20e';

-- Domain: atomic-shop.eu (Strategy: Pattern: 'atomic_shop')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('atomic_shop_eu_collections_racing_harnesses_report.pdf')
)
WHERE id = '7596c2ba-72b4-4d82-8b20-a7a70f8f3d00';

-- Domain: b2b.steam-one.nl (Strategy: Pattern: 'b2b')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('b2b_steam_one_nl_shop_report.pdf')
)
WHERE id = '99e4555c-d274-4ae2-809c-7c84114f59ba';

-- Domain: babybrezza.be (Strategy: Pattern: 'babybrezza')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('babybrezza_be_products_superfast_portable_warmer_report.pdf')
)
WHERE id = 'ee3ebe35-1c00-42a3-839d-64accb2018a2';

-- Domain: bodyworld.eu (Strategy: Pattern: 'bodyworld')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('bodyworld_eu_nl_en_nitric_oxide_c343_superior_14_t_report.pdf')
)
WHERE id = 'ad1b58d4-df07-44ce-9717-fdec1c93d1d5';

-- Domain: brouwerijwinkel.hertogjan.nl (Strategy: Pattern: 'brouwerijwinkel')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('brouwerijwinkel_hertogjan_nl_collections_all_report.pdf')
)
WHERE id = 'cf869e8f-d517-437d-a087-d5b9a604ffb1';

-- Domain: calex.eu (Strategy: Pattern: 'calex')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('calex_eu_report.pdf')
)
WHERE id = 'fe421137-0b09-4f27-b600-176105cb6ebd';

-- Domain: cosplayshop.be (Strategy: Pattern: 'cosplayshop')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('cosplayshop_be_nl_report.pdf')
)
WHERE id = 'a8338d45-5613-48f8-b47b-b9e50abc85b3';

-- Domain: credexalarmsystems.eu (Strategy: Pattern: 'credexalarmsystems')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('credexalarmsystems_eu_nl_blog_installeren_alarmsys_report.pdf')
)
WHERE id = '178f6b7c-597b-4dc3-8ad1-03458c454617';

-- Domain: cricketco.be (Strategy: Pattern: 'cricketco')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('cricketco_be_nl_pages_eshop_report.pdf')
)
WHERE id = '232ad622-813c-4e51-9c2f-48d3fee25ae5';

-- Domain: elro.eu (Strategy: Pattern: 'elro')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('elro_eu_en_security_lighting_report.pdf')
)
WHERE id = '8e357ecd-699e-41fc-8e15-9619a142ffa2';

-- Domain: homey.app (Strategy: Pattern: 'homey')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('homey_app_nl_nl_where_to_buy_report.pdf')
)
WHERE id = 'aa518013-13d3-46c3-8133-787bbd850b37';

-- Domain: hsnstore.eu (Strategy: Pattern: 'hsnstore')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('hsnstore_eu_sports_nutrition_weight_control_thermo_report.pdf')
)
WHERE id = '5037f669-ce94-4fdb-b443-fa2ddc8f82db';

-- Domain: huissteden.eu (Strategy: Pattern: 'huissteden')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('huissteden_eu_garen_vlies_embroidery_thread_report.pdf')
)
WHERE id = 'a3e0018f-df3e-4929-b711-74271c976123';

-- Domain: ip44.de (Strategy: Pattern: 'ip44')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('ip44_de_nl_report.pdf')
)
WHERE id = '2c44059e-e169-47c7-9557-c19aa0909847';

-- Domain: jdbrand.eu (Strategy: Pattern: 'jdbrand')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('jdbrand_eu_collections_stuurwielen_report.pdf')
)
WHERE id = '55e54f96-91ef-4685-8b83-8696fc22c35c';

-- Domain: koifarm.shop (Strategy: Pattern: 'koifarm')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('koifarm_shop_report.pdf')
)
WHERE id = '095aad64-981d-4d7e-a022-580408c9a9a7';

-- Domain: konnected.io (Strategy: Pattern: 'konnected')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('konnected_io_pages_hubitat_report.pdf')
)
WHERE id = '75686830-acfc-488c-a2a8-4ec2edad025e';

-- Domain: leaphy.store (Strategy: Pattern: 'leaphy')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('leaphy_store_product_rgb_led_single_report.pdf')
)
WHERE id = '142c3aab-6202-42ec-9335-ab3a3c5c57f6';

-- Domain: leefbewust.nu (Strategy: Pattern: 'leefbewust')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('leefbewust_nu_shop_report.pdf')
)
WHERE id = '79732bb2-4692-4289-9f1c-84b61849984e';

-- Domain: llli.org (Strategy: Pattern: 'llli')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('llli_org_nl_report.pdf')
)
WHERE id = '20655415-02d1-44fe-993c-87b04756d551';

-- Domain: marathonbasketbal.shop (Strategy: Pattern: 'marathonbasketbal')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('marathonbasketbal_shop_report.pdf')
)
WHERE id = 'ca641b44-7b58-411f-9fb4-f58a6db1ab3a';

-- Domain: marathonreizen.net (Strategy: Pattern: 'marathonreizen')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('marathonreizen_net_hardloopwinkels_report.pdf')
)
WHERE id = '74d09a93-f193-4b0e-94a0-4b9dfbe4a208';

-- Domain: mediacompany.motor.nl (Strategy: Pattern: 'mediacompany')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('mediacompany_motor_nl_report.pdf')
)
WHERE id = 'a16351e9-cf6e-42bd-a9e5-d98d5f1dd479';

-- Domain: meershop.eu (Strategy: Pattern: 'meershop')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('meershop_eu_product_tag_ethnic_report.pdf')
)
WHERE id = 'ffa78daa-5a66-4537-bb08-d55966c10538';

-- Domain: momsorganic.shop (Strategy: Pattern: 'momsorganic')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('momsorganic_shop_report.pdf')
)
WHERE id = '60093e07-f1f5-4629-8304-79d6be89b150';

-- Domain: mushingsupplies.eu (Strategy: Pattern: 'mushingsupplies')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('mushingsupplies_eu_neewa_adjustable_racing_harness_report.pdf')
)
WHERE id = 'a8ec1301-814d-4d35-8cd6-ef2042ce5520';

-- Domain: nl-musicshopeurope-beta.sanastores.net (Strategy: Pattern: 'nl_musicshopeurope_beta')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('nl_musicshopeurope_beta_sanastores_net_world_music_report.pdf')
)
WHERE id = 'a7f98f17-fd88-4cd5-9a78-7bb16de0e45f';

-- Domain: nlstore.hermanmiller.com (Strategy: Pattern: 'nlstore')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('nlstore_hermanmiller_com_pages_gaming_report.pdf')
)
WHERE id = '840bf144-09bb-4d16-a0c8-b98940643df3';

-- Domain: online-tuincentrum.be (Strategy: Pattern: 'online_tuincentrum')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('online_tuincentrum_be_report.pdf')
)
WHERE id = '92683c7b-5d01-4e1c-9f69-000195e76e37';

-- Domain: pelckmans.net (Strategy: Pattern: 'pelckmans')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('pelckmans_net_nl_196104_vijvertechniek_pond_led_li_report.pdf')
)
WHERE id = '9702d06a-86b0-4790-8e2f-f015cd9292ea';

-- Domain: portal.fullavl.nl (Strategy: Pattern: 'portal')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('portal_fullavl_nl_7_movingheads_report.pdf')
)
WHERE id = '0d96591f-812a-475f-b781-425b76be4133';

-- Domain: qshops.org (Strategy: Pattern: 'qshops')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('qshops_org_webshop_view_parfum_outlet_nl_report.pdf')
)
WHERE id = '639da2dc-6dc1-4a74-b19a-9e0b537c0b39';

-- Domain: recordcase.de (Strategy: Pattern: 'recordcase')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('recordcase_de_nl_dj_mixers_report.pdf')
)
WHERE id = 'bf049b2c-4015-408c-9527-a976c99b84c3';

-- Domain: repeat.audio (Strategy: Pattern: 'repeat')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('repeat_audio_report.pdf')
)
WHERE id = '4812e4f4-d187-45bf-813f-aa29f680a7a6';

-- Domain: rocketreach.co (Strategy: Pattern: 'rocketreach')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('rocketreach_co_daniel_lodders_email_80377099_report.pdf')
)
WHERE id = '2c1b3f29-3ae3-46f1-9715-bab703fb64ac';

-- Domain: sentidoninove.be (Strategy: Pattern: 'sentidoninove')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('sentidoninove_be_webshop_barbershop_php_report.pdf')
)
WHERE id = '2a788d20-4d65-422d-af21-2aecb1c231e8';

-- Domain: snelbalie.gps.nl (Strategy: Pattern: 'snelbalie')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('snelbalie_gps_nl_report.pdf')
)
WHERE id = '45abf5be-a4e4-42a2-b2fd-526a6742b4c7';

-- Domain: soxs.co (Strategy: Pattern: 'soxs')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('soxs_co_report.pdf')
)
WHERE id = '2c0dfb8f-1c0b-44c8-9cf0-48f7d88ccdb9';

-- Domain: sprinklr.co (Strategy: Pattern: 'sprinklr')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('sprinklr_co_products_tuinhandschoenen_report.pdf')
)
WHERE id = '9f0dc656-5cf5-4ad8-81f5-b7995f725877';

-- Domain: strengthshop.eu (Strategy: Pattern: 'strengthshop')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('strengthshop_eu_collections_powerlifting_report.pdf')
)
WHERE id = '06894c66-6874-48ae-9502-604f5deac55a';

-- Domain: surfpirates.de (Strategy: Pattern: 'surfpirates')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('surfpirates_de_nl_kitesurf_report.pdf')
)
WHERE id = '1d349f7b-e3f7-4e7c-a304-b2f602c90d51';

-- Domain: tfoa.eu (Strategy: Pattern: 'tfoa')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('tfoa_eu_report.pdf')
)
WHERE id = '91fb7cc4-e358-4d1f-8778-281128cc8789';

-- Domain: thebabystore.org (Strategy: Pattern: 'thebabystore')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('thebabystore_org_report.pdf')
)
WHERE id = '628d5fec-6c8d-4c0d-b077-97ee8a8760c2';

-- Domain: treatlife.tech (Strategy: Pattern: 'treatlife')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('treatlife_tech_report.pdf')
)
WHERE id = '741c295c-f66d-4964-a777-7c41bcd46c46';

-- Domain: u-buy.be (Strategy: Pattern: 'u_buy')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('u_buy_be_nl_brand_inovelli_report.pdf')
)
WHERE id = 'b657e20d-8feb-4938-bd14-8d8108d5b35b';

-- Domain: voetbaloa.clubwereld.nl (Strategy: Pattern: 'voetbaloa')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('voetbaloa_clubwereld_nl_report.pdf')
)
WHERE id = '0496ee70-4ec5-4467-8092-aba7f141e65c';

-- Domain: voordeligeautoonderdelen.be (Strategy: Pattern: 'voordeligeautoonderdelen')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('voordeligeautoonderdelen_be_contact_report.pdf')
)
WHERE id = 'c520cc0a-8e26-4e97-a5ed-09362090fb8f';

-- Domain: werkengeld.nu (Strategy: Pattern: 'werkengeld')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('werkengeld_nu_uitleg_report.pdf')
)
WHERE id = '7a75234f-e7c2-496d-900f-4c87bf6e1cda';

-- Domain: wmc.merchstore.nl (Strategy: Pattern: 'wmc')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('wmc_merchstore_nl_report.pdf')
)
WHERE id = '8bbef334-7d3a-4e65-8e5c-5c45f14d898c';

-- Domain: woltu.eu (Strategy: Pattern: 'woltu')
UPDATE leads
SET vars = jsonb_set(
    vars,
    '{report_filename}',
    to_jsonb('woltu_eu_nl_c_meubilair_slaapkamer_nachtkastjes_report.pdf')
)
WHERE id = 'a31df897-e25b-4406-ac57-0a9e8bc387a9';

