#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Match report filenames from Supabase Storage to leads database.
Generates SQL UPDATE statements to fix mismatches.
"""

import csv
import json
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Read CSV files
workspace_root = Path(__file__).parent.parent
storage_csv = workspace_root / "Supabase Snippet List Objects in Reports Bucket.csv"
leads_csv = workspace_root / "Supabase Snippet List Leads Table.csv"

# Load storage filenames
print("📂 Loading storage filenames...")
storage_files = []
with open(storage_csv, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        storage_files.append(row['name'])

print(f"✅ Found {len(storage_files)} files in Storage")

# Load leads
print("\n📋 Loading leads...")
leads = []
with open(leads_csv, 'r', encoding='utf-8') as f:
    reader = csv.DictReader(f)
    for row in reader:
        leads.append({
            'id': row['id'],
            'domain': row['domain'],
            'current_filename': row['report_filename'],
            'image_key': row['image_key']
        })

print(f"✅ Found {len(leads)} leads with report_filename")

# Matching logic
print("\n🔍 Matching leads to storage files...\n")

matches = []
mismatches = []
not_found = []

for lead in leads:
    domain = lead['domain']
    current_filename = lead['current_filename']
    
    # Normalize domain for matching
    # "koester-conceptstore.nl" → "koester_conceptstore_nl"
    normalized_domain = domain.replace('-', '_').replace('.com', '_com').replace('.nl', '_nl')
    
    # Find matching files in storage
    matching_files = [f for f in storage_files if f.startswith(normalized_domain) and f.endswith('_report.pdf')]
    
    if not matching_files:
        not_found.append({
            'lead': lead,
            'normalized': normalized_domain,
            'reason': 'No matching file found in storage'
        })
    elif len(matching_files) == 1:
        storage_filename = matching_files[0]
        
        if storage_filename == current_filename:
            matches.append({
                'lead': lead,
                'filename': storage_filename,
                'status': 'CORRECT'
            })
        else:
            mismatches.append({
                'lead': lead,
                'current': current_filename,
                'correct': storage_filename,
                'status': 'NEEDS_UPDATE'
            })
    else:
        not_found.append({
            'lead': lead,
            'normalized': normalized_domain,
            'candidates': matching_files,
            'reason': f'Multiple matches found ({len(matching_files)})'
        })

# Statistics
print("="*80)
print(f"📊 MATCHING RESULTS:")
print(f"  ✅ Correct:      {len(matches):4d} leads")
print(f"  🔧 Needs Update: {len(mismatches):4d} leads")
print(f"  ❌ Not Found:    {len(not_found):4d} leads")
print(f"  📦 Total:        {len(leads):4d} leads")
print("="*80)

# Show sample mismatches
if mismatches:
    print(f"\n🔧 SAMPLE MISMATCHES (showing first 10):\n")
    for i, item in enumerate(mismatches[:10]):
        print(f"{i+1}. Domain: {item['lead']['domain']}")
        print(f"   Current:  {item['current']}")
        print(f"   Correct:  {item['correct']}")
        print()

# Show not found
if not_found:
    print(f"\n❌ NOT FOUND (showing first 10):\n")
    for i, item in enumerate(not_found[:10]):
        print(f"{i+1}. Domain: {item['lead']['domain']}")
        print(f"   Normalized: {item['normalized']}")
        print(f"   Reason: {item['reason']}")
        if 'candidates' in item:
            print(f"   Candidates: {item['candidates']}")
        print()

# Generate SQL UPDATE statements
if mismatches:
    sql_file = workspace_root / "scripts" / "fix_report_filenames.sql"
    print(f"\n📝 Generating SQL UPDATE statements...")
    print(f"   Output: {sql_file}\n")
    
    with open(sql_file, 'w', encoding='utf-8') as f:
        f.write("-- SQL statements to fix report_filename mismatches\n")
        f.write("-- Generated by match_reports.py\n")
        f.write(f"-- Total updates: {len(mismatches)}\n\n")
        
        for item in mismatches:
            lead_id = item['lead']['id']
            domain = item['lead']['domain']
            correct_filename = item['correct']
            
            f.write(f"-- Domain: {domain}\n")
            f.write(f"UPDATE leads\n")
            f.write(f"SET vars = jsonb_set(\n")
            f.write(f"    vars,\n")
            f.write(f"    '{{report_filename}}',\n")
            f.write(f"    to_jsonb('{correct_filename}')\n")
            f.write(f")\n")
            f.write(f"WHERE id = '{lead_id}';\n\n")
        
        f.write(f"-- Verify updates:\n")
        f.write(f"-- SELECT domain, vars->>'report_filename' as report_filename\n")
        f.write(f"-- FROM leads\n")
        f.write(f"-- WHERE id IN (\n")
        for i, item in enumerate(mismatches):
            comma = ',' if i < len(mismatches) - 1 else ''
            f.write(f"--   '{item['lead']['id']}'{comma}\n")
        f.write(f"-- );\n")
    
    print(f"✅ SQL file created: {sql_file}")
    print(f"   Contains {len(mismatches)} UPDATE statements")

# Export detailed results to JSON
results_file = workspace_root / "scripts" / "report_matching_results.json"
print(f"\n💾 Exporting detailed results to JSON...")

results = {
    'summary': {
        'total_leads': len(leads),
        'correct': len(matches),
        'needs_update': len(mismatches),
        'not_found': len(not_found)
    },
    'matches': matches,
    'mismatches': mismatches,
    'not_found': not_found
}

with open(results_file, 'w', encoding='utf-8') as f:
    json.dump(results, f, indent=2, ensure_ascii=False)

print(f"✅ Results exported: {results_file}")

print("\n" + "="*80)
print("🎉 ANALYSIS COMPLETE!")
print("="*80)
print("\nNEXT STEPS:")
print("1. Review: scripts/report_matching_results.json")
print("2. Execute: scripts/fix_report_filenames.sql (via Supabase)")
print("3. Test: Send V1/V2/V3/V4 M3 templates to verify reports work")
print("="*80)
