#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Run SQL updates in batches via direct SQL execution.
Extracts UPDATE statements and runs them in manageable chunks.
"""

import re
import sys
from pathlib import Path

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Read SQL file
workspace_root = Path(__file__).parent.parent
sql_file = workspace_root / "scripts" / "fix_report_filenames.sql"

print("📂 Reading SQL file...")
with open(sql_file, 'r', encoding='utf-8') as f:
    content = f.read()

# Extract UPDATE statements - simpler approach
# Parse line by line and extract the data
lines = content.split('\n')
updates = []

current_domain = None
for i, line in enumerate(lines):
    if line.startswith('-- Domain:'):
        current_domain = line.replace('-- Domain:', '').strip()
    elif "to_jsonb('" in line and current_domain:
        # Extract filename
        filename_match = re.search(r"to_jsonb\('([^']+)'\)", line)
        if filename_match:
            filename = filename_match.group(1)
            # Look for WHERE id on next few lines
            for j in range(i, min(i+5, len(lines))):
                id_match = re.search(r"WHERE id = '([^']+)'", lines[j])
                if id_match:
                    lead_id = id_match.group(1)
                    updates.append((current_domain, filename, lead_id))
                    current_domain = None  # Reset
                    break

print(f"✅ Found {len(updates)} UPDATE statements")

# Generate batch SQL
batch_size = 100
batches = []

for i in range(0, len(updates), batch_size):
    batch = updates[i:i+batch_size]
    batch_sql = []
    
    for domain, filename, lead_id in batch:
        update = f"""UPDATE leads
SET vars = jsonb_set(vars, '{{report_filename}}', to_jsonb('{filename}'))
WHERE id = '{lead_id}';"""
        batch_sql.append(update)
    
    batches.append('\n'.join(batch_sql))

print(f"📦 Created {len(batches)} batches of {batch_size} updates each")

# Save batches to separate files for manual review
output_dir = workspace_root / "scripts" / "batches"
output_dir.mkdir(exist_ok=True)

print(f"\n💾 Saving batches to: {output_dir}")

for i, batch_sql in enumerate(batches):
    batch_file = output_dir / f"batch_{i+1:03d}_of_{len(batches):03d}.sql"
    with open(batch_file, 'w', encoding='utf-8') as f:
        f.write(f"-- Batch {i+1} of {len(batches)}\n")
        f.write(f"-- Updates: {len(batch_sql.split('UPDATE leads')) - 1}\n\n")
        f.write(batch_sql)
    print(f"  ✅ Saved: batch_{i+1:03d}_of_{len(batches):03d}.sql")

# Create a master combined file (smaller, without comments)
combined_file = workspace_root / "scripts" / "fix_report_filenames_combined.sql"
print(f"\n📝 Creating combined file...")

with open(combined_file, 'w', encoding='utf-8') as f:
    f.write("-- Combined SQL updates for report_filename fixes\n")
    f.write(f"-- Total updates: {len(updates)}\n")
    f.write("-- Generated by run_batch_updates.py\n\n")
    f.write("BEGIN;\n\n")
    
    for domain, filename, lead_id in updates:
        f.write(f"UPDATE leads SET vars = jsonb_set(vars, '{{report_filename}}', to_jsonb('{filename}')) WHERE id = '{lead_id}';\n")
    
    f.write("\nCOMMIT;\n")

print(f"✅ Combined file created: {combined_file}")

# Print summary
print("\n" + "="*80)
print("🎉 BATCH FILES READY!")
print("="*80)
print(f"\n📊 SUMMARY:")
print(f"  Total updates:    {len(updates)}")
print(f"  Batch size:       {batch_size}")
print(f"  Number of batches: {len(batches)}")
print(f"\n📁 FILES CREATED:")
print(f"  Individual batches: scripts/batches/batch_*.sql")
print(f"  Combined file:      scripts/fix_report_filenames_combined.sql")
print("\n💡 RECOMMENDATION:")
print("  Use the combined file for Supabase SQL Editor (has BEGIN/COMMIT)")
print("="*80)
